spring.application.name=dragon-head

channel.feishu.appId=cli_a93e931566785bcc
channel.feishu.appSecret=usZg6YbUgxVSMoL4ihiT5fSWT6zrDNJR
channel.feishu.robotOpenId=ou_ee35d0ed85f54152cb2cce7b2d363431
channel.feishu.whitelist=ou_ac7b80fe089073ac4354472602fc1862
channel.feishu.wakeWord=help
